name: Build and Test

on:
  push:
    branches:
      - main

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.BUCKET_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Tests
      run: |
        echo "variable from shell environment : $env_var"